// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"context"
	"encoding/json"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Psychics psychics
//
// swagger:model Psychics
type Psychics struct {

	// reliability
	Reliability int64 `json:"reliability,omitempty"`
}

// UnmarshalJSON unmarshals this object while disallowing additional properties from JSON
func (m *Psychics) UnmarshalJSON(data []byte) error {
	var props struct {

		// reliability
		Reliability int64 `json:"reliability,omitempty"`
	}

	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&props); err != nil {
		return err
	}

	m.Reliability = props.Reliability
	return nil
}

// Validate validates this psychics
func (m *Psychics) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this psychics based on context it is used
func (m *Psychics) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Psychics) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Psychics) UnmarshalBinary(b []byte) error {
	var res Psychics
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
