// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"context"
	"encoding/json"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ResponseСonceive response сonceive
//
// swagger:model ResponseСonceive
type ResponseСonceive struct {

	// hypothesis
	Hypothesis int64 `json:"hypothesis,omitempty"`
}

// UnmarshalJSON unmarshals this object while disallowing additional properties from JSON
func (m *ResponseСonceive) UnmarshalJSON(data []byte) error {
	var props struct {

		// hypothesis
		Hypothesis int64 `json:"hypothesis,omitempty"`
	}

	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&props); err != nil {
		return err
	}

	m.Hypothesis = props.Hypothesis
	return nil
}

// Validate validates this response сonceive
func (m *ResponseСonceive) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this response сonceive based on context it is used
func (m *ResponseСonceive) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ResponseСonceive) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResponseСonceive) UnmarshalBinary(b []byte) error {
	var res ResponseСonceive
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
