// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"context"
	"encoding/json"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ResponseSession response session
//
// swagger:model ResponseSession
type ResponseSession struct {

	// jwt
	Jwt string `json:"jwt,omitempty"`
}

// UnmarshalJSON unmarshals this object while disallowing additional properties from JSON
func (m *ResponseSession) UnmarshalJSON(data []byte) error {
	var props struct {

		// jwt
		Jwt string `json:"jwt,omitempty"`
	}

	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&props); err != nil {
		return err
	}

	m.Jwt = props.Jwt
	return nil
}

// Validate validates this response session
func (m *ResponseSession) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this response session based on context it is used
func (m *ResponseSession) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ResponseSession) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResponseSession) UnmarshalBinary(b []byte) error {
	var res ResponseSession
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
