// Code generated by go-swagger; DO NOT EDIT.

package server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"battle_of_psychics/openapi/models"
)

// ConceiveReader is a Reader for the Conceive structure.
type ConceiveReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ConceiveReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewConceiveOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewConceiveOK creates a ConceiveOK with default headers values
func NewConceiveOK() *ConceiveOK {
	return &ConceiveOK{}
}

/*
ConceiveOK describes a response with status code 200, with default header values.

OK
*/
type ConceiveOK struct {
	Payload []*models.ResponseСonceive
}

// IsSuccess returns true when this conceive o k response has a 2xx status code
func (o *ConceiveOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this conceive o k response has a 3xx status code
func (o *ConceiveOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this conceive o k response has a 4xx status code
func (o *ConceiveOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this conceive o k response has a 5xx status code
func (o *ConceiveOK) IsServerError() bool {
	return false
}

// IsCode returns true when this conceive o k response a status code equal to that given
func (o *ConceiveOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the conceive o k response
func (o *ConceiveOK) Code() int {
	return 200
}

func (o *ConceiveOK) Error() string {
	return fmt.Sprintf("[GET /Conceive][%d] conceiveOK  %+v", 200, o.Payload)
}

func (o *ConceiveOK) String() string {
	return fmt.Sprintf("[GET /Conceive][%d] conceiveOK  %+v", 200, o.Payload)
}

func (o *ConceiveOK) GetPayload() []*models.ResponseСonceive {
	return o.Payload
}

func (o *ConceiveOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
