// Code generated by go-swagger; DO NOT EDIT.

package server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewConceiveParams creates a new ConceiveParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewConceiveParams() *ConceiveParams {
	return &ConceiveParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewConceiveParamsWithTimeout creates a new ConceiveParams object
// with the ability to set a timeout on a request.
func NewConceiveParamsWithTimeout(timeout time.Duration) *ConceiveParams {
	return &ConceiveParams{
		timeout: timeout,
	}
}

// NewConceiveParamsWithContext creates a new ConceiveParams object
// with the ability to set a context for a request.
func NewConceiveParamsWithContext(ctx context.Context) *ConceiveParams {
	return &ConceiveParams{
		Context: ctx,
	}
}

// NewConceiveParamsWithHTTPClient creates a new ConceiveParams object
// with the ability to set a custom HTTPClient for a request.
func NewConceiveParamsWithHTTPClient(client *http.Client) *ConceiveParams {
	return &ConceiveParams{
		HTTPClient: client,
	}
}

/*
ConceiveParams contains all the parameters to send to the API endpoint

	for the conceive operation.

	Typically these are written to a http.Request.
*/
type ConceiveParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the conceive params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ConceiveParams) WithDefaults() *ConceiveParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the conceive params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ConceiveParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the conceive params
func (o *ConceiveParams) WithTimeout(timeout time.Duration) *ConceiveParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the conceive params
func (o *ConceiveParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the conceive params
func (o *ConceiveParams) WithContext(ctx context.Context) *ConceiveParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the conceive params
func (o *ConceiveParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the conceive params
func (o *ConceiveParams) WithHTTPClient(client *http.Client) *ConceiveParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the conceive params
func (o *ConceiveParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ConceiveParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
