// Code generated by go-swagger; DO NOT EDIT.

package server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGameParams creates a new GameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGameParams() *GameParams {
	return &GameParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGameParamsWithTimeout creates a new GameParams object
// with the ability to set a timeout on a request.
func NewGameParamsWithTimeout(timeout time.Duration) *GameParams {
	return &GameParams{
		timeout: timeout,
	}
}

// NewGameParamsWithContext creates a new GameParams object
// with the ability to set a context for a request.
func NewGameParamsWithContext(ctx context.Context) *GameParams {
	return &GameParams{
		Context: ctx,
	}
}

// NewGameParamsWithHTTPClient creates a new GameParams object
// with the ability to set a custom HTTPClient for a request.
func NewGameParamsWithHTTPClient(client *http.Client) *GameParams {
	return &GameParams{
		HTTPClient: client,
	}
}

/*
GameParams contains all the parameters to send to the API endpoint

	for the game operation.

	Typically these are written to a http.Request.
*/
type GameParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the game params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GameParams) WithDefaults() *GameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the game params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GameParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the game params
func (o *GameParams) WithTimeout(timeout time.Duration) *GameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the game params
func (o *GameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the game params
func (o *GameParams) WithContext(ctx context.Context) *GameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the game params
func (o *GameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the game params
func (o *GameParams) WithHTTPClient(client *http.Client) *GameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the game params
func (o *GameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
