// Code generated by go-swagger; DO NOT EDIT.

package server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"battle_of_psychics/openapi/models"
)

// GetSessionReader is a Reader for the GetSession structure.
type GetSessionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSessionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetSessionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetSessionOK creates a GetSessionOK with default headers values
func NewGetSessionOK() *GetSessionOK {
	return &GetSessionOK{}
}

/*
GetSessionOK describes a response with status code 200, with default header values.

Success create session
*/
type GetSessionOK struct {
	Payload *models.ResponseSession
}

// IsSuccess returns true when this get session o k response has a 2xx status code
func (o *GetSessionOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get session o k response has a 3xx status code
func (o *GetSessionOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get session o k response has a 4xx status code
func (o *GetSessionOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get session o k response has a 5xx status code
func (o *GetSessionOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get session o k response a status code equal to that given
func (o *GetSessionOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get session o k response
func (o *GetSessionOK) Code() int {
	return 200
}

func (o *GetSessionOK) Error() string {
	return fmt.Sprintf("[GET /Session][%d] getSessionOK  %+v", 200, o.Payload)
}

func (o *GetSessionOK) String() string {
	return fmt.Sprintf("[GET /Session][%d] getSessionOK  %+v", 200, o.Payload)
}

func (o *GetSessionOK) GetPayload() *models.ResponseSession {
	return o.Payload
}

func (o *GetSessionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseSession)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
