// Code generated by go-swagger; DO NOT EDIT.

package server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"battle_of_psychics/openapi/models"
)

// ConceiveOKCode is the HTTP code returned for type ConceiveOK
const ConceiveOKCode int = 200

/*
ConceiveOK OK

swagger:response conceiveOK
*/
type ConceiveOK struct {

	/*
	  In: Body
	*/
	Payload []*models.ResponseСonceive `json:"body,omitempty"`
}

// NewConceiveOK creates ConceiveOK with default headers values
func NewConceiveOK() *ConceiveOK {

	return &ConceiveOK{}
}

// WithPayload adds the payload to the conceive o k response
func (o *ConceiveOK) WithPayload(payload []*models.ResponseСonceive) *ConceiveOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the conceive o k response
func (o *ConceiveOK) SetPayload(payload []*models.ResponseСonceive) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ConceiveOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.ResponseСonceive, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

func (o *ConceiveOK) ConceiveResponder() {}

type ConceiveNotImplementedResponder struct {
	middleware.Responder
}

func (*ConceiveNotImplementedResponder) ConceiveResponder() {}

func ConceiveNotImplemented() ConceiveResponder {
	return &ConceiveNotImplementedResponder{
		middleware.NotImplemented(
			"operation authentication.Conceive has not yet been implemented",
		),
	}
}

type ConceiveResponder interface {
	middleware.Responder
	ConceiveResponder()
}
