// Code generated by go-swagger; DO NOT EDIT.

package server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"battle_of_psychics/openapi/models"
)

// ConceiveHandlerFunc turns a function with the right signature into a conceive handler
type ConceiveHandlerFunc func(ConceiveParams, *models.Principal) ConceiveResponder

// Handle executing the request and returning a response
func (fn ConceiveHandlerFunc) Handle(params ConceiveParams, principal *models.Principal) ConceiveResponder {
	return fn(params, principal)
}

// ConceiveHandler interface for that can handle valid conceive params
type ConceiveHandler interface {
	Handle(ConceiveParams, *models.Principal) ConceiveResponder
}

// NewConceive creates a new http.Handler for the conceive operation
func NewConceive(ctx *middleware.Context, handler ConceiveHandler) *Conceive {
	return &Conceive{Context: ctx, Handler: handler}
}

/*
	Conceive swagger:route GET /Conceive server conceive

Conceive conceive API
*/
type Conceive struct {
	Context *middleware.Context
	Handler ConceiveHandler
}

func (o *Conceive) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewConceiveParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
