// Code generated by go-swagger; DO NOT EDIT.

package server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"battle_of_psychics/openapi/models"
)

// GameHandlerFunc turns a function with the right signature into a game handler
type GameHandlerFunc func(GameParams, *models.Principal) GameResponder

// Handle executing the request and returning a response
func (fn GameHandlerFunc) Handle(params GameParams, principal *models.Principal) GameResponder {
	return fn(params, principal)
}

// GameHandler interface for that can handle valid game params
type GameHandler interface {
	Handle(GameParams, *models.Principal) GameResponder
}

// NewGame creates a new http.Handler for the game operation
func NewGame(ctx *middleware.Context, handler GameHandler) *Game {
	return &Game{Context: ctx, Handler: handler}
}

/*
	Game swagger:route GET /Game server game

Game game API
*/
type Game struct {
	Context *middleware.Context
	Handler GameHandler
}

func (o *Game) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGameParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
