// Code generated by go-swagger; DO NOT EDIT.

package server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"battle_of_psychics/openapi/models"
)

// GetSessionOKCode is the HTTP code returned for type GetSessionOK
const GetSessionOKCode int = 200

/*
GetSessionOK Success create session

swagger:response getSessionOK
*/
type GetSessionOK struct {

	/*
	  In: Body
	*/
	Payload *models.ResponseSession `json:"body,omitempty"`
}

// NewGetSessionOK creates GetSessionOK with default headers values
func NewGetSessionOK() *GetSessionOK {

	return &GetSessionOK{}
}

// WithPayload adds the payload to the get session o k response
func (o *GetSessionOK) WithPayload(payload *models.ResponseSession) *GetSessionOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get session o k response
func (o *GetSessionOK) SetPayload(payload *models.ResponseSession) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSessionOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *GetSessionOK) GetSessionResponder() {}

type GetSessionNotImplementedResponder struct {
	middleware.Responder
}

func (*GetSessionNotImplementedResponder) GetSessionResponder() {}

func GetSessionNotImplemented() GetSessionResponder {
	return &GetSessionNotImplementedResponder{
		middleware.NotImplemented(
			"operation authentication.GetSession has not yet been implemented",
		),
	}
}

type GetSessionResponder interface {
	middleware.Responder
	GetSessionResponder()
}
