// Code generated by go-swagger; DO NOT EDIT.

package server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"battle_of_psychics/openapi/models"
)

// GetSessionHandlerFunc turns a function with the right signature into a get session handler
type GetSessionHandlerFunc func(GetSessionParams, *models.Principal) GetSessionResponder

// Handle executing the request and returning a response
func (fn GetSessionHandlerFunc) Handle(params GetSessionParams, principal *models.Principal) GetSessionResponder {
	return fn(params, principal)
}

// GetSessionHandler interface for that can handle valid get session params
type GetSessionHandler interface {
	Handle(GetSessionParams, *models.Principal) GetSessionResponder
}

// NewGetSession creates a new http.Handler for the get session operation
func NewGetSession(ctx *middleware.Context, handler GetSessionHandler) *GetSession {
	return &GetSession{Context: ctx, Handler: handler}
}

/*
	GetSession swagger:route GET /Session server getSession

GetSession get session API
*/
type GetSession struct {
	Context *middleware.Context
	Handler GetSessionHandler
}

func (o *GetSession) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetSessionParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
