// Code generated by go-swagger; DO NOT EDIT.

// Package restapi battle
//
//	Service The battle of psychics
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /
//	Version: 1.0.0
//
//	Consumes:
//	  - application/json
//	  - application/x-www-form-urlencoded
//
//	Produces:
//	  - text/html
//	  - application/json
//
// swagger:meta
package restapi
